# Generated by Django 4.2.7 on 2025-07-20 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='loans_loan_user_id_d0fb34_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['book', 'status'], name='loans_loan_book_id_f87641_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='loans_loan_due_dat_1042a5_idx'),
        ),
    ]
